Repository safespace-marcy/safespace, pull requests merged in 2020-05, with the labels that each got.

#22 (doc) Adds wireframe to README and endpoint docs
  README.md
  wireframe.png
Labels: documentation

#24 references altered in table definitions in README
  README.md
Labels: documentation

#25 (feat) Adds user-controller
  controllers/userController.js
  package-lock.json
  package.json
Labels: back-end

#31 Refactors User Controller
  controllers/userController.js
  middleware/authenticate.js
  models/User.js
  package.json
  server.js
Labels: back-end, enhancement

#38 (feat) Adds Router to Server
  controllers/userController.js
  routes/postRouter.js
  routes/userRouter.js
  server.js
Labels: back-end

#39 (fix) tested user API and added nodemon dependency
  client/public/index.html
  controllers/userController.js
  db.js
  middleware/authenticate.js
  models/User.js
  package-lock.json
  package.json
  routes/userRouter.js
  server.js
Labels: back-end, bug

#40 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#42 (feat/fix) Feature Package
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/index.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  controllers/postController.js
  routes/userRouter.js
Labels: back-end, bug, front-end

#45 (feat#34)new post form
  README.md
  client/package-lock.json
  client/src/components/WritePostForm.js
  client/src/index.js
  controllers/postController.js
  models/Posts.js
Labels: back-end, enhancement, front-end

#46 (feat) adds Register form
  client/public/index.html
  client/src/App.js
  client/src/components/Register.js
Labels: enhancement, front-end

#47 Feat/user-context
  client/src/App.js
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/components/Logout.js
  client/src/components/Navbar.js
  client/src/components/Register.js
  client/src/contexts/userContext.js
Labels: enhancement, front-end

#51 (feat) add new post form modal to community page
  client/src/components/NewPostModal.js
  client/src/components/NewsFeed.js
  client/src/components/Post.js
  client/src/components/WritePostForm.js
  controllers/postController.js
Labels: enhancement, front-end

#54 (refactor-#48) added redirect feature on register and login
  client/package-lock.json
  client/package.json
  client/src/components/Login.js
  client/src/components/Register.js
  controllers/userController.js
  env.example
Labels: front-end

#55 Fixes Logout on Refresh Bug
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Login.js
  client/src/components/Register.js
  client/src/contexts/userContext.js
  controllers/userController.js
Labels: bug, front-end

#58 Refac/post yoga styles
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Login.js
  client/src/components/NewPostModal.js
  client/src/components/NewsFeed.js
  client/src/components/Register.js
  client/src/components/WritePostForm.js
  client/src/contexts/userContext.js
  controllers/userController.js
Labels: front-end

#57 Feat/community routes
  .DS_Store
  .gitignore
  controllers/communitiesController.js
  controllers/userController.js
  routes/communitiesRouter.js
Labels: back-end

#68 Form Design Overhaul
  client/package-lock.json
  client/src/App.js
  client/src/components/Communities.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/components/NewsFeed.js
  client/src/components/Register.js
  client/src/contexts/userContext.js
  controllers/communitiesController.js
  routes/communitiesRouter.js
  server.js
Labels: enhancement, front-end

#69 install knex, add migrations, remove raw sql from readme
  README.md
  knexfile.js
  package-lock.json
  package.json
  src/README.md
  src/db/migrations/20200519104957_create_users_table.js
  src/db/migrations/20200519110934_create_communities_table.js
  src/db/migrations/20200519111854_create_posts_table.js
  src/db/migrations/20200519120743_create_community_users_table.js
Labels: back-end

#71 Feat/seeds
  client/src/components/Communities.js
  knexfile.js
  src/README.md
  src/db/migrations/20200519110934_create_communities_table.js
  src/db/migrations/20200519111854_create_posts_table.js
  src/db/seeds/01_seeds.js
  src/db/seeds/02_communities.js
  src/db/seeds/03_posts.js
  src/db/seeds/04_community_users.js
Labels: Setup, back-end

#72 Feat/Spaces
  client/src/App.js
  client/src/components/Communities.js
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  package-lock.json
  package.json
Labels: enhancement, front-end

#73 (feat-#70) created Account component
  client/src/App.js
  client/src/components/Account.js
  client/src/components/Login.js
  controllers/postController.js
  routes/postRouter.js
Labels: front-end

#75 (feat/merge) Merges all components
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Communities.js
  client/src/components/Landing.js
  client/src/components/Navbar.js
  client/src/components/NewsFeed.js
Labels: enhancement, front-end

#77 Feature package
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/styles.css
  client/src/App.js
  client/src/components/Account.js
  client/src/components/AvatarGen.js
  client/src/components/Communities.js
  client/src/components/Community.js
  client/src/components/Home.js
  client/src/components/Landing.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/components/NewsFeed.js
  client/src/components/Post.js
  client/src/components/Register.js
  client/src/components/Theme.js
  client/src/index.js
  models/Communities.js
  package-lock.json
  package.json
Labels: enhancement, front-end

#79 (feat - #78&66) added read more and visit users account
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Account.js
  client/src/components/NewsFeed.js
  client/src/components/OtherUserAcc.js
  client/src/components/Post.js
  controllers/userController.js
  routes/userRouter.js
Labels: back-end, enhancement, front-end

#80 Chat Feature
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/styles.css
  client/src/App.js
  client/src/components/Account.js
  client/src/components/Chat.js
  client/src/components/Community.js
  client/src/components/Home.js
  client/src/components/Landing.js
  client/src/components/Message.js
  client/src/components/Navbar.js
  client/src/components/NewsFeed.js
  client/src/components/Post.js
  client/src/components/Register.js
  package-lock.json
  package.json
  server.js
  socketManager.js
Labels: back-end, enhancement, front-end

#87 (Feat) Adds UI features to chat
  client/public/feather-alt-solid.svg
  client/public/index.html
  client/src/components/Chat.js
  client/src/components/Message.js
  socketManager.js
Labels: enhancement, front-end
